---

- name: Make hadoop directory
  file:
    path: "/opt/hadoop-{{ hadoop_tools_hadoop_version }}"
    state: directory
    mode: '0755'
  tags:
    - directory

- name: Download and unarchive hadoop tarball
  unarchive:
    src: "{{ hadoop_tools_hadoop_tarball_url }}"
    dest: "/opt/hadoop-{{ hadoop_tools_hadoop_version }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags:
    - install

- name: Add Hadoop path to env
  copy:
    dest: /etc/profile.d/hadoop_bin.sh
    content: "export PATH=$PATH:/opt/hadoop-{{ hadoop_tools_hadoop_version }}/bin"
  tags:
    - env
