---
  
- name: Install java
  import_role:
    name: java
  tags:
    - hadoop-tools-java

- include_tasks: hadoop.yml
  tags:
    - hadoop-tools-hadoop

- include_tasks: hive.yml
  tags:
    - hadoop-tools-hive

- include_tasks: spark.yml
  tags:
    - hadoop-tools-spark

- include_tasks: oozie-client.yml
  tags:
    - hadoop-tools-oozie-client
