---
  
- include: java.yml
  tags:
    - hadoop-tools-java

- include: hadoop.yml
  tags:
    - hadoop-tools-hadoop

- include: hive.yml
  tags:
    - hadoop-tools-hive

- include: spark.yml
  tags:
    - hadoop-tools-spark

- include: oozie-client.yml
  tags:
    - hadoop-tools-oozie-client
