---
- name: Make oozie directory
  file:
    path: "/usr/local/src/oozie-{{ hadoop_tools_oozie_version }}"
    state: directory
    mode: '0755'

- name: Download and unarchive hadoop tarball
  unarchive:
    src: "{{ hadoop_tools_oozie_tarball_url }}"
    dest: "/usr/local/src/oozie-{{ hadoop_tools_oozie_version }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "/usr/local/src/oozie-{{ hadoop_tools_oozie_version }}/pom.xml"

- name: Add Centos Base repo to install Maven from
  yum_repository:
    name: centos-base
    description: Centos Base repo
    file: Centos-Base
    mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
    gpgcheck: yes
    gpgkey: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7

- name: Install Maven to build the oozie client
  yum:
    name: maven
    state: latest

- name: Fix repositories to use https instead of http
  replace:
    path: "/usr/local/src/oozie-{{ hadoop_tools_oozie_version }}/pom.xml"
    regexp: 'http://(?=repo1.maven.org)'
    replace: 'https://'

- name: Build oozie client tarball
  command: "mvn assembly:assembly -Dmaven.test.skip=true"
  args:
    chdir: "/usr/local/src/oozie-{{ hadoop_tools_oozie_version }}/client"
    creates: "/usr/local/src/oozie-{{ hadoop_tools_oozie_version }}/client/target/oozie-client-{{ hadoop_tools_oozie_version }}-client"

- name: Move oozie client to more appropriate location
  command: "mv /usr/local/src/oozie-{{ hadoop_tools_oozie_version }}/client/target/oozie-client-{{ hadoop_tools_oozie_version }}-client/oozie-client-{{ hadoop_tools_oozie_version }} /opt"
  args:
    creates: "/opt/oozie-client-{{ hadoop_tools_oozie_version }}"

- name: Add oozie binary to path
  copy:
    dest: /etc/profile.d/oozie_bin.sh
    content: "export PATH=$PATH:/opt/oozie-client-{{ hadoop_tools_oozie_version }}/bin"


